const id=new URLSearchParams(location.search).get('project')||'focus';
const demo=document.querySelector('#demo');
const header=name=>`<header><a href="./">${name}</a><span>Working sample / Bangkok #3</span></header>`;
document.body.className=id;
let timer;
if(id==='focus'){
  document.title='Little Focus | working sample';
  demo.innerHTML=header('little focus')+'<main><h1>A little room to focus.</h1><div class="timer" role="timer">25:00</div><div class="controls"><button id="start">Start session</button><button id="reset">Reset</button></div><p class="hint">One thing at a time is enough.</p></main>';
  let remaining=1500;const draw=()=>document.querySelector('.timer').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
  document.querySelector('#start').onclick=()=>{if(timer){clearInterval(timer);timer=null;document.querySelector('#start').textContent='Resume';}else{document.querySelector('#start').textContent='Pause';timer=setInterval(()=>{remaining=Math.max(0,remaining-1);draw();if(!remaining){clearInterval(timer);timer=null;document.querySelector('#start').textContent='Session complete';}},1000);}};
  document.querySelector('#reset').onclick=()=>{clearInterval(timer);timer=null;remaining=1500;draw();document.querySelector('#start').textContent='Start session';};
}else if(id==='bites'){
  document.title='Bangkok Bites | working sample';
  demo.innerHTML=header('bangkok bites')+'<main><h1>Good lunch. Close by.</h1><p>Sample neighborhood picks for a hungry afternoon.</p><div class="filters"><button aria-pressed="true" data-filter="all">All picks</button><button aria-pressed="false" data-filter="rice">Rice</button><button aria-pressed="false" data-filter="noodles">Noodles</button></div><div class="meal-grid"><article class="meal" data-category="rice"><h2>Basil & rice</h2><p>A familiar favorite.<br>Example price</p><strong>฿65</strong><button data-save>Save for lunch</button></article><article class="meal" data-category="noodles"><h2>Noodle corner</h2><p>A bowl worth a break.<br>Example price</p><strong>฿70</strong><button data-save>Save for lunch</button></article><article class="meal" data-category="rice"><h2>Market lunch</h2><p>Simple and satisfying.<br>Example price</p><strong>฿60</strong><button data-save>Save for lunch</button></article></div></main>';
  document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));document.querySelectorAll('.meal').forEach(meal=>meal.hidden=button.dataset.filter!=='all'&&meal.dataset.category!==button.dataset.filter);});
  document.querySelectorAll('[data-save]').forEach(button=>button.onclick=()=>{const saved=button.getAttribute('aria-pressed')==='true';button.setAttribute('aria-pressed',String(!saved));button.textContent=saved?'Save for lunch':'Saved';});
}else if(id==='palette'){
  document.title='Color Pocket | working sample';
  demo.innerHTML=header('color pocket')+'<main><h1>A pair with possibility.</h1><p>Two colors. Something new.</p><div class="pair"><div class="swatch"><strong>Aa</strong><button data-copy="#346569">#346569</button></div><div class="swatch"><strong>Aa</strong><button data-copy="#F4DCAE">#F4DCAE</button></div></div><div class="controls"><p>Lagoon / Butter</p><button id="next">Next pair</button></div><p class="copy-feedback" role="status"></p></main>';
  const pairs=[['#346569','#F4DCAE','Lagoon / Butter'],['#514269','#E8DCEA','Plum / Lilac'],['#304F3A','#D8E59F','Pine / Meadow']];let current=0;
  document.querySelector('#next').onclick=()=>{current=(current+1)%pairs.length;const [a,b,name]=pairs[current];document.querySelectorAll('.swatch').forEach((swatch,i)=>{swatch.style.background=i?b:a;swatch.style.color=i?a:b;const button=swatch.querySelector('button');button.textContent=i?b:a;button.dataset.copy=i?b:a;});document.querySelector('.controls p').textContent=name;};
}else if(id==='garden'){
  document.title='Pocket Garden | working sample';demo.innerHTML=header('pocket garden')+'<main><div class="garden-panel"><h1>A little care grows.</h1><p id="garden-state" role="status">The community garden is ready for a drink.</p><button id="water">Water the garden</button></div></main>';let count=0;document.querySelector('#water').onclick=()=>{count++;document.querySelector('#garden-state').textContent=`Garden watered ${count} time${count===1?'':'s'}. Thanks for stopping by!`;};
}else if(id==='shelf'){
  document.title='Prompt Shelf | working sample';demo.innerHTML=header('prompt shelf')+'<main><h1>Good starting points.</h1><p>Keep a useful thought within reach.</p><div class="prompt-list"><article class="prompt-row"><div><h2>Make it clearer</h2><p>Rewrite this paragraph in plain language. Keep the meaning, cut the extra words.</p></div><button data-copy="Rewrite this paragraph in plain language. Keep the meaning, cut the extra words.">Copy</button></article><article class="prompt-row"><div><h2>Find the edge case</h2><p>Read this function. What input could make it fail, and why?</p></div><button data-copy="Read this function. What input could make it fail, and why?">Copy</button></article><article class="prompt-row"><div><h2>Start small</h2><p>Break this idea into the smallest useful first version.</p></div><button data-copy="Break this idea into the smallest useful first version.">Copy</button></article></div><p class="copy-feedback" role="status"></p></main>';
}else{
  document.title='Small Steps | working sample';demo.innerHTML=header('small steps')+'<main><div><h1>A good day, one small step.</h1><p>Start wherever you are. The little things count.</p></div><div><div class="tasks"><label class="task"><input type="checkbox"><span>Drink a glass of water</span></label><label class="task"><input type="checkbox"><span>Go outside for five minutes</span></label><label class="task"><input type="checkbox"><span>Make something small</span></label><label class="task"><input type="checkbox"><span>Say thank you to someone</span></label></div><span class="progress-copy" role="status">0 of 4 little things</span><button id="reset">Start a fresh day</button></div></main>';
  const update=()=>document.querySelector('.progress-copy').textContent=`${document.querySelectorAll('input:checked').length} of 4 little things`;document.querySelectorAll('input').forEach(input=>input.onchange=update);document.querySelector('#reset').onclick=()=>{document.querySelectorAll('input').forEach(input=>input.checked=false);update();};
}
demo.addEventListener('click',async event=>{const button=event.target.closest('[data-copy]');if(!button)return;const status=document.querySelector('.copy-feedback');try{await navigator.clipboard.writeText(button.dataset.copy);status.textContent='Copied to clipboard.';}catch{status.textContent=`Copy this text: ${button.dataset.copy}`;}});
